export default {
    props:{
        prop:{
            type:String,
            default:''  
        },
        lable:{
            type:String,
            default:''
        },
        value:{
            type:String,
            default:''
        },
        row:{
            type:JSON,
            default:{}
        },
    }
}